preload = /home/luis11/Imagens/wallpapers/painting-mountain-lake-with-mountain-background.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-blitzboy-1144176.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-pixabay-301375.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-lastly-937782.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-life-of-pix-7919.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-invisiblepower-1076885.jpg
preload = /home/luis11/Imagens/wallpapers/manjaro-cat.jpg
preload = /home/luis11/Imagens/wallpapers/pexels-fotios-photos-1266302.jpg



wallpaper = eDP-1,/home/luis11/Imagens/wallpapers/pexels-fotios-photos-1266302.jpg

exec-once = hyprpaper

