[opener]
edit = [
    { run = '/sbin/nvim "$@"', block = true, desc = "Edit with Neovim" }
]
# pdf = [
#     { run = 'tdf "$@"', desc = "Abrir PDF com tdf", block=true },
#     { run = 'xdg-open "$@"', desc = "Open with default app" }
# ]
pdf = [
    { run = 'tdf "$@"', desc = "Abrir PDF com tdf", block = true },
    { run = 'zathura "$@"', desc = "Zathura", orphan = true },
    { run = 'xdg-open "$@"', desc = "Open with default app" }
]

image = [
    { run = 'nomacs "$@"', desc = "View with nomacs" },
    { run = 'xdg-open "$@"', desc = "Open with default app" }
]
text = [
    { run = '/sbin/nvim "$@"', block = true, desc = "Edit with Neovim" }
]
gnuplot = [
    { run = '/sbin/nvim "$@"', block = true, desc = "Edit with Neovim" }
]

# djvu = [
#     { run = 'atril "$@"', desc = "Abrir DJVU com Atril", block = false }
# ]

djvu = [
    { run = 'zathura "$@"', orphan = true },
    { run = 'atril "$@"', desc = "Abrir com Atril", orphan = true }
]

[open]
rules = [
    { url = "*/", use = "folder" },
    # PDFs e DjVu
    { mime = "application/pdf", use = "pdf" },
    { mime = "image/vnd.djvu", use = "pdf" },
    { url = "*.djvu", use = "pdf" },

    # Imagens
    { mime = "image/*", use = "image" },
    # Textos para editar
    { mime = "text/*", use = "edit" },
    { url = "*.txt", use = "edit" },
    { url = "*.md", use = "edit" },
    { url = "*.py", use = "edit" },
    { url = "*.sh", use = "edit" },
    { url = "*.toml", use = "edit" },
    { url = "*.yaml", use = "edit" },
    { url = "*.yml", use = "edit" },
    { url = "*.ipynb", use = "edit" },
    { url = "*.json", use = "edit" },
    { url = "*.js", use = "edit" },
    { url = "*.css", use = "edit" },
    { url = "*.html", use = "edit" },
    # Gnuplot
    { url = "*.gp", use = "gnuplot" },
    { url = "*.plt", use = "gnuplot" },
    { url = "*.gnuplot", use = "gnuplot" },
]

[plugin]
prepend_fetchers = [
  { id = "git", group = "file", url = "*", run = "git" },
  { id = "git", group = "directory", url = "*/", run = "git" },
]
