return {
  "jakewvincent/mkdnflow.nvim",
  ft = { "markdown" },
  config = function()
    require("mkdnflow").setup({
      modules = {
        bib        = true,
        buffers    = true,
        conceal    = true,
        cursor     = true,
        folds      = true,
        gonna      = true,
        links      = true,
        lists      = true,
        maps       = true,
        paths      = true,
        tables     = true,
        yaml       = true,
      },
      filetypes = { md = true, markdown = true },
      create_dirs = true,
      perspective = {
        priority = "first",
        fallback = "current",
      },
      links = {
        style           = "markdown",
        conceal         = false,
        context         = 0,
        implicit_extension = nil,
        transform_implicit = false,
        transform_explicit = function(text)
          text = text:gsub(" ", "-")
          text = text:lower()
          return text
        end,
      },
      tables = {
        trim_whitespace      = true,
        format_on_move       = true,
        auto_extend_rows     = false,
        auto_extend_cols     = false,
      },
      mappings = {
        MkdnEnter          = { { "n", "v" }, "<CR>" },
        MkdnTab            = { "i", "<Tab>" },
        MkdnSTab           = { "i", "<S-Tab>" },
        MkdnNextLink       = { "n", "<Tab>" },
        MkdnPrevLink       = { "n", "<S-Tab>" },
        MkdnNextHeading    = { "n", "]]" },
        MkdnPrevHeading    = { "n", "[[" },
        MkdnGoBack         = { "n", "<BS>" },
        MkdnGoForward      = { "n", "<Del>" },
        MkdnCreateLink     = false,
        MkdnCreateLinkFromClipboard = { { "n", "v" }, "<leader>mP" },
        MkdnFollowLink     = false,
        MkdnDestroyLink    = { "n", "<leader>md" },
        MkdnTagSpan        = false,
        MkdnMoveSource     = false,
        MkdnYankFileAnchorLink = { "n", "<leader>my" },
        MkdnNewListItem    = false,
        MkdnNewListItemBelowInsert = { "n", "o" },
        MkdnNewListItemAboveInsert = { "n", "O" },
        MkdnExtendList     = false,
        MkdnUpdateNumbering = { "n", "<leader>mn" },
        MkdnToggleToDo     = { { "n", "v" }, "<leader>mt" },
        MkdnTableNextCell  = { "i", "<Tab>" },
        MkdnTablePrevCell  = { "i", "<S-Tab>" },
        MkdnTableNextRow   = false,
        MkdnTablePrevRow   = { "i", "<M-CR>" },
        MkdnTableNewRowBelow = { "n", "<leader>mir" },
        MkdnTableNewRowAbove = { "n", "<leader>miR" },
        MkdnTableNewColAfter = { "n", "<leader>mic" },
        MkdnTableNewColBefore = { "n", "<leader>miC" },
        MkdnFoldSection    = { "n", "<leader>mf" },
        MkdnUnfoldSection  = { "n", "<leader>mF" },
      },
    })
  end,
}
